"""Prompts do Apura — reexporta camadas (política / protocolo / voz / orquestrador)."""

from apura.prompts import (  # noqa: F401
    NARRATIVA_ORCHESTRATOR,
    POLITICA_DADOS,
    PROTOCOLO_AIRY_CRIACAO,
    PROTOCOLO_AIRY_ELEITORAL,
    PROTOCOLO_ANALISTA,
    PROTOCOLO_OPERACIONAL,
    RECORTE_BRASIL,
    SKILL_CAMPANHA_IDENTIDADE,
    SKILL_NARRATIVA_DEFAULT,
    SKILL_WAR_ROOM_DEFAULT,
    SYSTEM_ORCHESTRATOR,
    SYSTEM_WRITER,
    VOZ_OPERACIONAL,
    VOZ_REDATOR,
)

__all__ = [
    "NARRATIVA_ORCHESTRATOR",
    "SYSTEM_ORCHESTRATOR",
    "SYSTEM_WRITER",
    "VOZ_REDATOR",
    "VOZ_OPERACIONAL",
    "SKILL_WAR_ROOM_DEFAULT",
    "SKILL_NARRATIVA_DEFAULT",
    "SKILL_CAMPANHA_IDENTIDADE",
    "POLITICA_DADOS",
    "RECORTE_BRASIL",
    "PROTOCOLO_AIRY_ELEITORAL",
    "PROTOCOLO_AIRY_CRIACAO",
    "PROTOCOLO_OPERACIONAL",
    "PROTOCOLO_ANALISTA",
]
